config/routes.rb
Rails.application.routes.draw do
  get 'product/new' => "product#new"
  post 'product/create' => "product#create"

  get "login" => "home#login"

  get 'record' => "home#record"
  post "record/create" => "home#create"

  get "graph" => "home#graph"
  get "graph_select" => "home#graph_select"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/defect.rb
class Defect < ApplicationRecord
  belongs_to :record
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :prodcut
  has_many :defects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
  end

  def record
    @product = Product.new
    @record = Record.new
  end

  def create
    @record = Record.new(
      prod_name: params[:prod_name],
      date: params[:date],
      yield: params[:yield],
      def_total: params[:def_total]
    )

    if @record.save
      if params[:def_type].present?
        @defect = Defect.new(
          record_id: Record.all.last.id,
          date: Record.all.last.date,
          def_type: params[:def_type],
          def_count: params[:def_count]
          )
        flash[:notice] = "製造記録登録が完了しました"
        redirect_to("/record")
      end
    else
      render("record/record")
    end
  end

  def graph
    @product = Product.new
    @record = Record.all
    @record_a = Record.where(prod_name: "Aricept")
    @record_b = Record.where(prod_name: "metycobal")
    @record_c = Record.where(prod_name: "myonal")

    @data = [
      {
        date: @record_a.pluck(:date),
        def_total: @record_a.pluck(:def_total)
      },
      {
        date: @record_b.pluck(:date),
        def_total: @record_b.pluck(:def_total)
      }
    ]
  end

  def graph_select
    @product = Product.new
    @record = Record.where(prod_name: params[:search])
    redirect_to("/graph_select")
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(
      prod_name: params[:prod_name]
    )
    if @product.save
      flash[:notice] = "製品登録が完了しました"
      redirect_to("/product/new")
    else
      render("product/new")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/home/graph.html.erb
<p id="notice"><%= notice %></p>

<div class="cotainer">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header">KPI時系列推移</div>
                <div class="card-body">
                  <div class="form-group row">
                      <label for="prod_name" class="col-md-4 col-form-label text-md-right">品目選択</label>
                      <div class="col-md-6 test3">
                        <%= form_for @product, url: product_new_path do |f| %>
                          <%= f.collection_select :prod_name, Product.all, :id, :prod_name, {}, class: "form-control", :include_blank => true %>
                        <% end %>
                      </div>
                      <!--
                      <script>
                      $(".test3").on("change", function() {
                          var prod_name = $('option:selected').val();

                      });
                      </script>
                      -->
                  </div>
                  <div class="form-group row">
                      <label for="date" class="col-md-2 col-form-label text-md-left">収率</label>
                      <div class="col-md-10">
                        <%= line_chart Record.pluck(:date, :yield) %>
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="date" class="col-md-2 col-form-label text-md-left">不良総計</label>
                      <div class="col-md-10">
                        <%= column_chart Record.pluck(:date, :def_total) %>
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="date" class="col-md-2 col-form-label text-md-left">不良内訳</label>
                      <div class="col-md-10">
                        <%= column_chart @data, stacked: true %>
                      </div>
                  </div>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/graph_select.html.erb
<p id="notice"><%= notice %></p>

<div class="cotainer">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header">KPI時系列推移</div>
                <div class="card-body">
                  <div class="form-group row">
                      <label for="prod_name" class="col-md-4 col-form-label text-md-right">品目選択</label>
                      <%= form_tag("/graph_select",:method => 'get') do %>
                        <%= text_field_tag :search %>
                        <%= submit_tag 'Search', :name => nil %>
                      <% end %>
                      <div class="col-md-6 test3">
                        <%= form_for @product, url: product_new_path do |f| %>
                          <%= f.collection_select :prod_name, Product.all, :id, :prod_name, {}, class: "form-control", include_blank: true, selected: @record.prod_name %>
                        <% end %>
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="date" class="col-md-2 col-form-label text-md-left">収率</label>
                      <div class="col-md-10">
                        <%= line_chart @record.pluck(:date, :yield) %>
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="date" class="col-md-2 col-form-label text-md-left">不良総計</label>
                      <div class="col-md-10">
                        <%= column_chart @record.pluck(:date, :def_total) %>
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="date" class="col-md-2 col-form-label text-md-left">不良内訳</label>
                      <div class="col-md-10">
                        <%= column_chart @data, stacked: true %>
                      </div>
                  </div>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/login.html.erb
<head>

  <!------ コピペしてきたBootstrap CSS ---------->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!------ コピペしてきたBootstrap CSS ---------->

  <link rel="stylesheet" href="assets/stylesheets.login.css">

</head>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Register</div>
                    <div class="card-body">
                        <form action="" method="">
                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>
                                <div class="col-md-6">
                                    <input type="text" id="email_address" class="form-control" name="email-address" required autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                <div class="col-md-6">
                                    <input type="password" id="password" class="form-control" name="password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember"> Remember Me
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                                <a href="#" class="btn btn-link">
                                    Forgot Your Password?
                                </a>
                            </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

</main>

app/views/home/record.html.erb
<div class="cotainer">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">本日の製造記録データを下記フォームに記入してください。</div>
                <div class="card-body">

                    <%= form_with @record, url: record_create_path do |f| %>
                        <div class="form-group row">
                            <label for="date" class="col-md-4 col-form-label text-md-right">製造日</label>
                            <div class="col-md-6">
                                <input type="text" id="date" class="form-control" name="date" value="<%= Date.today %>" required autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="prod_name" class="col-md-4 col-form-label text-md-right">製造品目</label>
                            <div class="col-md-6">
                              <%= form_with @product, url: record_path do |f| %>
                                <%= f.collection_select :prod_name, Product.all, :prod_name, :prod_name, {class: "form-control", include_blank: true} %>
                              <% end %>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lot" class="col-md-4 col-form-label text-md-right">ロット番号</label>
                            <div class="col-md-6">
                                <input type="text" id="lot" class="form-control" name="lot" placeholder="例) 11A22M" required autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="input_vol" class="col-md-4 col-form-label text-md-right">投入量</label>
                            <div class="col-md-6">
                                <input type="text" id="input_vol" class="form-control" name="input_vol" value="" placeholder="例) 10000" required autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="output_vol" class="col-md-4 col-form-label text-md-right">出来高</label>
                            <div class="col-md-6">
                                <input type="text" id="output_vol" class="form-control" name="output_vol" value="" placeholder="例) 5000" required autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="yield" class="col-md-4 col-form-label text-md-right">収率</label>
                            <div class="col-md-6">
                                <input type="text" id="yield" class="form-control" name="yield" value="" readonly required autofocus>
                            </div>
                            <script>
                            $(function() {
                              $('input[type="text"]').change(function() {
                                var o = $("#output_vol").val();
                                var i = $("#input_vol").val();
                                var so = parseInt(o);
                                var si = parseInt(i);
                                var result = so/si;
                                $('#yield').val(result.toFixed(2));
                              });
                            });
                            </script>
                        </div>
                        <div class="form-group row">
                            <label for="def_total" class="col-md-4 col-form-label text-md-right">不良総計</label>
                            <div class="col-md-6">
                                <input type="text" id="def_total" class="form-control" name="def_total" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-5 offset-md-4">
                              <table>
                                  <tbody>
                                      <tr>
                                        <td>種類内訳</td>
                                        <td>不良数</td>
                                      </tr>
                                      <tr>
                                          <td><input type="text" class="form-control" name="def_type" required autofocus></td>
                                          <td><input type="text" class="form-control" name="def_count" required autofocus></td>
                                          <td><button class="remove">-</button></td>
                                      </tr>
                                  </tbody>
                              </table>
                              <button id="addRow">+ 追加</button>
                            <script>
                            $(function(){
                                $('#addRow').click(function(){
                                    var html = '<tr><td><input type="text" name="name" class="form-control" name="def_type" required autofocus></td><td><input type="text" name="name" class="form-control" name="def_count" required autofocus></td><td><button class="remove">-</button></td></tr>';
                                    $('tbody').append(html);
                                });
                                $(document).on('click', '.remove', function() {
                                    $(this).parents('tr').remove();
                                });
                            });
                            </script>
                            </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-md-3 offset-md-9">
                            <input type="submit" value="記録する" class="btn btn-primary">
                          </div>
                        </div>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaizenApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="assets/stylesheets.home.css">
    <!------ コピペしてきたBootstrap CSS ---------->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ コピペしてきたBootstrap CSS ---------->

    <!-- 自分んで貼ったBootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!------ コピペしてきたJQueryのCDNリンク ---------->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <!------ コピペしてきたJQueryのCDNリンク ---------->

  </head>

  <body>
    <header>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-10">
            <div class="row justify-content-center">
              <div class="col-md-2 align-center">
                <%= link_to("製造記録", "/record") %>
              </div>
              <div class="col-md-2 align-center">
                <%= link_to("時系列グラフ", "/graph") %>
              </div>
              <div class="col-md-2 align-center">
                <%= link_to("新規製品登録", "/product/new") %>
              </div>
              <div class="col-md-2 align-center">
                <%= link_to("新規ユーザー登録", "/user/new") %>
              </div>
              <div class="col-md-2 align-center">
                <%= link_to("ログイン", "/login") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <hr class="bothline">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>

    <hr class="bothline">

    <div class="container">
      <footer>
        <p>&copy; 2020 space</p>
      </footer>
    </div>

  </body>

</html>

app/views/product/new.html.erb
<head>

  <!------ コピペしてきたBootstrap CSS ---------->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!------ コピペしてきたBootstrap CSS ---------->

  <link rel="stylesheet" href="assets/stylesheets.login.css">

</head>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">新規製品登録</div>
                    <div class="card-body">

                      <div class="form-group row">
                        <div class="col-md-6">
                          <%= form_with model: @product, url: product_create_path do |f| %>
                            <%= f.collection_select :prod_name, Product.all, :prod_name, :prod_name, {class: "form-control", include_blank: true} %>
                            <%= f.submit %>
                          <% end %>
                        </div>
                      </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</main>